<?php
/**
 * Error handler & debuger class
 */

namespace oreym\debug;

class Debug
{
    public function __construct()
    {
        error_reporting(0);
        ob_start();
        set_error_handler( [$this, 'errorHandler'] );
        register_shutdown_function( [$this, 'fatalErrorHandler'] );
        set_exception_handler( [$this, 'exeptionHandler'] );
    }

    /**
     * Error code to text conversion method
     * @param int $errno   error code
     * @return string
     */
    private function errorType ( $errno )
    {
        $errors = array(
            E_ERROR => '[ERROR] Fatal error',
            E_WARNING => '[WARNING] Runtime warnings (not fatal errors)',
            E_PARSE => '[PARSE] Error parsing source code',
            E_NOTICE => '[NOTICE] Possible error while executing code',
            E_CORE_ERROR => '[CORE ERROR] Fatal PHP interpreter launch error',
            E_CORE_WARNING => '[CORE WARNING] Warning when running PHP interpreter',
            E_COMPILE_ERROR => '[COMPILE ERROR] Fatal compile error',
            E_COMPILE_WARNING => '[COMPILE WARNING] Warning at compile time',
            E_USER_ERROR => '[USERERROR] User generated error',
            E_USER_WARNING => '[USER WARNING] User generated warning',
            E_USER_NOTICE => '[USER NOTICE] User generated notice',
            E_STRICT => '[STRICT] Runtime Notification',
            E_RECOVERABLE_ERROR => '[RECOVERABLE ERROR] Catch fatal error',
            E_DEPRECATED => '[DEPRECATED] Use of obsolete structures',
            E_USER_DEPRECATED => '[USER DEPRECATED] Using obsolete designs generated by the user',
            'Exception' => '[Exception] Call exception'
        );

        return $errors[$errno];
    }

    /**
     * Method to check if a fatal error occurred
     * @return array|bool
     */
    private function checkFatalError ()
    {
        return ( $error = error_get_last() ) && $error['type'] & ( E_ERROR | E_PARSE | E_COMPILE_ERROR | E_CORE_ERROR)  ? $error : FALSE;
    }

    /**
     * Method for generating data output for debugging an array or object
     * @param array|object $data debug data
     * @param array $newArray data to output
     */
    private static function varExtract ( $data, &$newArray )
    {

        foreach ($data as $key => $value)
        {
            $type = gettype($value);
            $indexType = gettype($key);

            if ( is_object($data) )
            {
                $key = "->{$key}";
            }
            else
            {
                $key = $indexType === 'integer' ? "[{$key}]" : "['{$key}']";
            }

            switch($type)
            {
                case 'boolean':
                    $value = $value ? 'TRUE' : 'FALSE';
                    $newArray[] = "<tr><td class=\"boolean\">({$type})</td><td>{$key}</td><td>=></td><td>{$value}</td></tr>";
                break;

                case 'integer':
                    $newArray[] = "<tr><td class=\"integer\">({$type})</td><td>{$key}</td><td>=></td><td>{$value}</td></tr>";
                break;

                case 'double':
                    $newArray[] = "<tr><td class=\"double\">({$type})</td><td>{$key}</td><td>=></td><td>{$value}</td></tr>";
                break;

                case 'string':
                    $strlen = strlen( $value );
                    if ( $strlen > 38 )
                    {
                        $newArray[] = '</tbody></table>';
                        $newArray[] = '<details class="long-string">';
                            $newArray[] = "<summary><span class=\"string\">({$type})</span> {$key} ::: <span>Length [{$strlen}]. Detail:</span></summary>";
                            $newArray[] = "<summary>{$value}</summary>";
                        $newArray[] = '</details>';
                        $newArray[] = '<table><tbody>';
                    }
                    else
                    {
                        $newArray[] = "<tr><td class=\"string\">({$type})</td><td>{$key}</td><td>=></td><td>{$value}</td></tr>";
                    }

                break;

                case 'resource':
                    $resType = get_resource_type($value);
                    $newArray[] = '</tbody></table>';
                    $newArray[] = '<details class="offset">';
                        $newArray[] = "<summary class=\"resource\">|Resource| {$key} (Resource type: {$resType})</summary>";
                        $newArray[] = "<summary>{$value}</summary>";
                    $newArray[] = '</details>';
                    $newArray[] = '<table><tbody>';
                break;

                case 'NULL':
                    $newArray[] = "<tr><td class=\"null\">({$type})</td><td>{$key}</td><td>=></td><td>No value</td></tr>";
                break;

                case 'unknown type':
                    $newArray[] = "<tr><td class=\"unknown - type\">({$type})</td><td>{$key}</td><td>=></td><td>Unknown type</td></tr>";
                break;

                case 'array':
                    $newArray[] = '</tbody></table>';
                    $newArray[] = '<details class=\"offset\">';
                    $newArray[] = "<summary class=\"array\">[Array] {$key} (Length: " . count($value) . ')</summary>';

                    $newArray[] = '<table><tbody>';
                    self::varExtract ( $value, $newArray );
                    $newArray[] = '</tbody></table>';

                    $newArray[] = '</details>';
                    $newArray[] = '<table><tbody>';
                break;

                case 'object':
                    $newArray[] = '</tbody></table>';
                    $newArray[] = '<details class=\"offset\">';
                    $newArray[] = "<summary class=\"object\">{Object} {$key} (Length: " . count($value) . ')</summary>';

                    $newArray[] = '<table><tbody>';
                    self::varExtract ( $value, $newArray );
                    $newArray[] = '</tbody></table>';

                    $newArray[] = '</details>';
                    $newArray[] = '<table><tbody>';
                break;
            }
        }
    }

    /**
     * Error output
     * @param int $errno   error code
     * @param string $errstr   error text
     * @param string $errfile   the file where the error occurred
     * @param int $errline   the line where the error occurred
     * @param int $response   server code
     * @return void
     */
    protected function showError ( $errno, $errstr, $errfile, $errline, $response = 0 )
    {
        $errType = $this->errorType( $errno );

        require_once 'error/style.php';
        require 'error/devError.php';
    }

    /**
     * Error logging method
     * @param int $errno   error code
     * @param string $errstr   error text
     * @param string $errfile   the file where the error occurred
     * @param int $errline   the line where the error occurred
     */
    protected function errorsLog ( $errno, $errstr, $errfile, $errline )
    {
        $errLogStr =
            '[' . date( 'Y-m-d H:i:s' ) . '] Error text: ' . $errstr . ' File: ' . $errfile . ' | Line: ' . $errline;

//        error_log( $errLogStr . "\n", 3, '/log/error.log');
    }

    /**
     * Error handling method
     * @param int $errno   error code
     * @param string $errstr   error text
     * @param string $errfile   the file where the error occurred
     * @param int $errline   the line where the error occurred
     * @return bool
     */
    public function errorHandler ( $errno, $errstr, $errfile, $errline )
    {
        $this->errorsLog( $errno, $errstr, $errfile, $errline );
        $this->showError( $errno, $errstr, $errfile, $errline );

        return TRUE;
    }

    /**
     * Fatal error handling method
     * @return void
     */
    public function fatalErrorHandler ()
    {
        if ( FALSE !== ( $error = $this->checkFatalError() ) )
        {
            $this->errorsLog( $error['type'], $error['message'], $error['file'], $error['line'] );
            $this->showError( $error['type'], $error['message'], $error['file'], $error['line'] );
        }
    }

    /**
     * Exception handling method
     * @param \Exception $e
     */
    public function exeptionHandler ( $e )
    {
        $this->errorsLog( 'Exception', $e->getMessage(), $e->getFile(), $e->getLine() );
        $this->showError( 'Exception', $e->getMessage(), $e->getFile(), $e->getLine(), $e->getCode() );
    }

    /**
     * Debug output method
     * @param mixed ...$debugData   debug data
     */
    public static function debug( ...$debugData )
    {
        $backtrace = debug_backtrace();
        $debugInfo = array();

        foreach ( $debugData as $data )
        {
            switch ( gettype( $data ) )
            {
                case 'integer':
                    $debugInfo = [
                        'varType' => gettype( $data ),
                        'var' => $data
                    ];
                break;
                case 'double':
                    $debugInfo = [
                        'varType' => gettype( $data ),
                        'var' => $data
                    ];
                break;
                case 'string':
                    $debugInfo = [
                        'varType' => gettype( $data ),
                        'var' => $data
                    ];
                break;
                case 'boolean':
                    $debugInfo = [
                        'varType' => gettype( $data ),
                        'var' => $data ? 'TRUE' : 'FALSE'
                    ];
                break;
                case 'NULL':
                    $debugInfo = [
                        'varType' => gettype( $data ),
                        'addInfoType' => ' | Variable without value',
                        'var' => 'NULL'
                    ];
                break;
                case 'resource':
                    $debugInfo = [
                        'varType' => gettype( $data ),
                        'addInfoType' => ' | Link to external resource',
                        'var' => get_resource_type($data)
                    ];
                break;
                case 'unknown type':
                    $debugInfo = [
                        'varType' => gettype( $data ),
                        'addInfoType' => ' | Unknown data type',
                        'var' => FALSE
                    ];
                break;
                case 'array':
                    $newArray = array();
                    $newArray[] = '<details open class="offset"><summary class="array">[Array] (Length: ' . count
                        ($data) . ')</summary>';

                    $newArray[] = '<table><tbody>';
                    self::varExtract ( $data, $newArray );
                    $newArray[] = '</tbody></table></details>';

                    $debugInfo = [
                        'varType' => gettype( $data ),
                        'addInfoType' => ' | Array',
                        'var' => $newArray
                    ];

                break;
                case 'object':
                    $newArray = array();
                    $newArray[] = '<details open class="offset"><summary class="array">{Object} (Length: ' . count
                        ($data) . ')</summary>';

                    $newArray[] = '<table><tbody>';
                    self::varExtract ( $data, $newArray );
                    $newArray[] = '</tbody></table></details>';

                    $debugInfo = [
                        'varType' => gettype( $data ),
                        'addInfoType' => ' | Object',
                        'var' => $newArray
                    ];

                break;
            }
            require_once 'error/style.php';
            require 'error/debug.php';
        }
    }
}